# ──────────────────────────────────────────────────────────────────────────────
# project_generator.py — Development Spec -> Full Project Generator
#
# Generates complete multi-file software project structures (Backend, Frontend, CLI, APIs)
# based on natural language developmental specifications.
# ──────────────────────────────────────────────────────────────────────────────
from config import BASE_DIR
import os
import re
import json
from typing import Dict, List, Optional

DEFAULT_PROJECTS_DIR = os.environ.get("VARIC_PROJECTS_DIR", str(BASE_DIR.parent / "VaricProjects"))


class ProjectGenerator:
    def __init__(self, base_dir: str = DEFAULT_PROJECTS_DIR):
        self.base_dir = base_dir

    def sanitize_name(self, name: str) -> str:
        """Sanitize project directory name."""
        clean = re.sub(r'[^a-zA-Z0-9_\-]', '_', name.strip().lower())
        return clean or "generated_project"

    def generate_project_structure(self, spec: str, project_name: Optional[str] = None) -> Dict:
        """
        Parses project specification and generates files and directory structure.
        """
        # Determine name
        name_match = re.search(r'(?:name|called|project|app)\s+([a-zA-Z0-9_\-]+)', spec, re.IGNORECASE)
        name = project_name or (name_match.group(1) if name_match else "ai_generated_app")
        clean_name = self.sanitize_name(name)
        target_path = os.path.join(self.base_dir, clean_name)

        os.makedirs(target_path, exist_ok=True)
        print(f"[PROJECT GENERATOR] Building '{clean_name}' at {target_path}...")

        # Detect project type / tech stack
        spec_lower = spec.lower()
        if "react" in spec_lower or "vite" in spec_lower or "frontend" in spec_lower:
            files = self._template_react_vite(clean_name, spec)
        elif "fastapi" in spec_lower or "python" in spec_lower or "api" in spec_lower or "backend" in spec_lower:
            files = self._template_fastapi(clean_name, spec)
        elif "node" in spec_lower or "express" in spec_lower:
            files = self._template_express(clean_name, spec)
        else:
            files = self._template_general_python(clean_name, spec)

        # Write files
        from utils.file_utils import write_project_files
        created_files = write_project_files(target_path, files)

        print(f"[PROJECT GENERATOR READY] Generated {len(created_files)} files in {target_path}")
        return {
            "status": "ok",
            "project_name": clean_name,
            "target_path": target_path,
            "files_created": created_files,
            "message": f"Successfully generated full project '{clean_name}' with {len(created_files)} files."
        }

    def _template_fastapi(self, name: str, spec: str) -> Dict[str, str]:
        return {
            "main.py": f'''# {name} — FastAPI Backend
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import uvicorn

app = FastAPI(title="{name.title()}")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

class Item(BaseModel):
    title: str
    description: str = ""

items_db = []

@app.get("/")
def read_root():
    return {{"status": "online", "project": "{name}"}}

@app.get("/items")
def get_items():
    return {{"items": items_db}}

@app.post("/items")
def create_item(item: Item):
    items_db.append(item.dict())
    return {{"status": "created", "item": item}}

if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=8000)
''',
            "requirements.txt": "fastapi>=0.100.0\nuvicorn>=0.22.0\npydantic>=2.0.0\nrequests\n",
            "README.md": f"# {name.title()}\n\nAutogenerated by Varic Project Generator.\n\n## Specification\n{spec}\n\n## Running the Project\n```bash\npip install -r requirements.txt\npython main.py\n```\n",
            ".gitignore": "__pycache__/\n*.pyc\n.env\nvenv/\n.venv/\n"
        }

    def _template_react_vite(self, name: str, spec: str) -> Dict[str, str]:
        return {
            "index.html": f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{name.title()}</title>
</head>
<body>
  <div id="root"></div>
  <script type="module" src="/src/main.jsx"></script>
</body>
</html>
''',
            "src/main.jsx": '''import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
''',
            "src/App.jsx": f'''import React, {{ useState }} from 'react'

export default function App() {{
  const [count, setCount] = useState(0)

  return (
    <div style={{{{ padding: '2rem', fontFamily: 'sans-serif', textAlign: 'center' }}}}>
      <h1>🚀 {name.title()}</h1>
      <p>{spec}</p>
      <button onClick={{() => setCount(count + 1)}} style={{{{ padding: '0.5rem 1rem', fontSize: '1rem', cursor: 'pointer' }}}}>
        Clicked {{count}} times
      </button>
    </div>
  )
}}
''',
            "src/index.css": '''body { margin: 0; background: #0f172a; color: #f8fafc; font-family: system-ui, sans-serif; }''',
            "package.json": json.dumps({
                "name": name,
                "private": True,
                "version": "1.0.0",
                "type": "module",
                "scripts": {
                    "dev": "vite",
                    "build": "vite build"
                },
                "dependencies": {
                    "react": "^18.2.0",
                    "react-dom": "^18.2.0"
                },
                "devDependencies": {
                    "@vitejs/plugin-react": "^4.0.0",
                    "vite": "^4.3.0"
                }
            }, indent=2),
            "README.md": f"# {name.title()}\n\n{spec}\n\n## Run\n```bash\nnpm install\nnpm run dev\n```\n"
        }

    def _template_express(self, name: str, spec: str) -> Dict[str, str]:
        return {
            "index.js": f'''const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());

app.get('/', (req, res) => {{
  res.json({{ status: 'online', project: '{name}' }});
}});

app.listen(PORT, () => {{
  console.log(`Server running on http://localhost:${{PORT}}`);
}});
''',
            "package.json": json.dumps({
                "name": name,
                "version": "1.0.0",
                "main": "index.js",
                "scripts": { "start": "node index.js" },
                "dependencies": { "express": "^4.18.2" }
            }, indent=2),
            "README.md": f"# {name.title()}\n\n{spec}\n\n## Run\n```bash\nnpm install\nnpm start\n```\n"
        }

    def _template_general_python(self, name: str, spec: str) -> Dict[str, str]:
        return {
            "main.py": f'''# {name} — Python Application
import sys

def main():
    print("🚀 {name.title()} started.")
    print("Specification: {spec}")

if __name__ == "__main__":
    main()
''',
            "requirements.txt": "# Add dependencies here\n",
            "README.md": f"# {name.title()}\n\n{spec}\n\n## Run\n```bash\npython main.py\n```\n"
        }


project_generator = ProjectGenerator()

if __name__ == "__main__":
    res = project_generator.generate_project_structure("Create a FastAPI analytics dashboard called AnalyticsApp")
    print("Project Result:", res)
